/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
import { IItem } from "./components/category-item/category-item";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface CategoryColumn {
        "column": string;
        "items": IItem[];
    }
    interface CategoryItem {
        "name": string;
        "status": string;
    }
    interface CategoryPanel {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCategoryColumnElement extends Components.CategoryColumn, HTMLStencilElement {
    }
    var HTMLCategoryColumnElement: {
        prototype: HTMLCategoryColumnElement;
        new (): HTMLCategoryColumnElement;
    };
    interface HTMLCategoryItemElement extends Components.CategoryItem, HTMLStencilElement {
    }
    var HTMLCategoryItemElement: {
        prototype: HTMLCategoryItemElement;
        new (): HTMLCategoryItemElement;
    };
    interface HTMLCategoryPanelElement extends Components.CategoryPanel, HTMLStencilElement {
    }
    var HTMLCategoryPanelElement: {
        prototype: HTMLCategoryPanelElement;
        new (): HTMLCategoryPanelElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "category-column": HTMLCategoryColumnElement;
        "category-item": HTMLCategoryItemElement;
        "category-panel": HTMLCategoryPanelElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface CategoryColumn {
        "column": string;
        "items": IItem[];
    }
    interface CategoryItem {
        "name"?: string;
        "status"?: string;
    }
    interface CategoryPanel {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "category-column": CategoryColumn;
        "category-item": CategoryItem;
        "category-panel": CategoryPanel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "category-column": LocalJSX.CategoryColumn & JSXBase.HTMLAttributes<HTMLCategoryColumnElement>;
            "category-item": LocalJSX.CategoryItem & JSXBase.HTMLAttributes<HTMLCategoryItemElement>;
            "category-panel": LocalJSX.CategoryPanel & JSXBase.HTMLAttributes<HTMLCategoryPanelElement>;
        }
    }
}
